plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.jlink' version '3.0.1'
}

repositories {
    mavenCentral()
}

javafx {
    version = "17"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'net.jockx.kulki.MainApp'
    mainModule = 'net.jockx.kulki'
}

group = 'net.jockx'
version = '1.0.2'

description = """Kulki"""

dependencies {
    implementation 'org.openjfx:javafx-controls:17'
    implementation 'org.openjfx:javafx-fxml:17'
    implementation 'com.miglayout:miglayout-javafx:11.2'
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    implementation 'org.slf4j:slf4j-simple:2.0.17'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

test {
    useJUnitPlatform()
}

compileJava {
    options.encoding = 'UTF-8'
}

jlink {
    options = ['--strip-debug', '--no-header-files', '--no-man-pages']
    addExtraDependencies('org.slf4j')
    launcher {
        name = 'Kulki'
    }

    jpackage {
        skipInstaller = true
        icon = 'flatpak/Kulki.png'
        imageOptions += [
                '--app-content', 'flatpak/Kulki.desktop',
                '--app-content', 'flatpak/Kulki.metainfo.xml'
        ]
    }
}

tasks.register('packageTarGz', Tar) {
    group = 'Distribution'
    description = 'Creates a tar.gz archive of the jpackage image for Flatpak builds.'
    dependsOn jpackage

    from layout.buildDirectory.dir('jpackage/Kulki')
    into 'Kulki'

    archiveBaseName = 'Kulki'
    archiveVersion = project.version
    archiveExtension = 'tar.gz'
    compression = Compression.GZIP

    destinationDirectory = layout.buildDirectory.dir('distributions')
}

tasks.register("buildFlatpak") {
    group = 'Build'
    description = 'Builds and installs a Flatpak package from the jpackage image.'
    dependsOn packageTarGz

    doLast {
        def buildDirFile = layout.buildDirectory.get().asFile
        def flatpakDir = new File(buildDirFile, 'flatpak')
        flatpakDir.mkdirs()

        copy {
            from layout.buildDirectory.dir('distributions')
            include "Kulki-${project.version}.tar.gz"
            into flatpakDir
            rename "Kulki-${project.version}.tar.gz", "kulki.tar.gz"
        }

        copy {
            from "flatpak/"
            include "net.jockx.Kulki.yml"
            into flatpakDir
        }

        exec {
            workingDir flatpakDir
            commandLine 'flatpak', 'remote-add', '--if-not-exists', '--user', 'flathub',
                    'https://dl.flathub.org/repo/flathub.flatpakrepo'
        }
        exec {
            workingDir flatpakDir
            commandLine 'flatpak', 'install', '--user', 'org.flatpak.Builder'
        }
        exec {
            workingDir flatpakDir
            commandLine 'flatpak', 'run', 'org.flatpak.Builder', '--force-clean', '--user',
                    '--install-deps-from=flathub',
                    '--state-dir=.flatpak-builder',
                    '--repo=repo',
                    '--install', 'builddir', 'net.jockx.Kulki.yml'
        }
    }
}
